title: Fahrin Andiwijaya
logo: assets/images/pict_1.jpg
#description: epidemiology, disability studies and rehabilitation
description: > # this means to ignore newlines until "show_exerpts:"
theme: jekyll-theme-minimal
